### ISSUE TITLE
Export to service from outside psql

### ISSUE THREAD

**Issue by pgiraud** [agneum/plan-exporter#11]
Is there a way we could use `plan-exporter` outside `psql`?

My goal: running a query which is saved in a file.

The command would probably look like:
```
psql -f my_explain_file.sql | plan-exporter --target=dalibo
```
Do you see any way I could this working?

As a workaround, what I currently do is:
```
postgres=# \o | plan-exporter
postgres=# \i my_explain_file.sql
```

**Comment by agneum** [comment]
@pgiraud Thanks for the question. Currently, an execution plan can only be published to the visualizer after confirmation in `psql`. This approach requires interaction.

However, there is a way to solve this problem.
We could add a special option to `plan-exporter` (say `--auto-publish`). If this flag is enabled, a plan will be sent automatically without additional confirmation.

Thus, this improvement will allow the exporter to be used outside `psql`.

**Comment by pgiraud** [comment]
> We could add a special option to `plan-exporter` (say `--auto-publish`).

I was thinking about something like this as well. That's a good idea in my opinion.

What about `-y` | `--yes` | `--assume-yes` (like for `apt`) or `-c` | `--auto-confirm` ? This are just suggestions.

**Comment by agneum** [comment]
@pgiraud Thanks for what great suggestions. I added the `--auto-confirm` flag. You can try out it in v0.0.5. 
Please check https://github.com/agneum/plan-exporter#command-line-options for more details.

**Comment by pgiraud** [comment]
Excellent! Thank you very much for this addition.
