### ISSUE TITLE
"target" in welcome message may not be accurate

### ISSUE THREAD

**Issue by pgiraud** [agneum/plan-exporter#13]
Sometimes I like to use a service running on my own machine, thus I set `--post-url`.
In the next line, the welcome message tells me that the mentioned target is still "depesz".
This is a very minor issue which doesn't really need to be fixed. It's easy to understand that this is not taken into account.

```
temboard=# \o | plan-exporter --post-url=http://0.0.0.0:5000/new
temboard=# Welcome to the query plan exporter. Target: depesz.
```

I see 2 options to solve this:
 - get rid of the `--port-url` option and use `--target` all the time. The utility would then check if it's a known target, or would consider it as a URL instead.
 - change the welcome message and show the post-url instead of the target.

**Comment by agneum** [comment]
Thanks for the issue. The `--target` option additionally describes the format of HTTP requests to the visualizer. Unfortunately, that's the reason why we cannot delegate URL definition to the `--target` parameter and get rid of `--port-url`.

I think we could add a specific URL to the welcome message if `--port-url` is different from the default.
